#!/bin/bash

# Script to start the skywire mainnet

# now load it
. /etc/default/skywire
. /etc/skybian.conf

# Function to return the manager/node argument based on the IP
# we get it from the ifconfig command beacuse se the IP config may
# vary in the future (dhcp|static_interface|static-interface.d/*)
function get_mode() {
    # get the IP
    local IP=`hostname -I | awk '{ print $1 }'`

    # check if we are on a manager or a node
    if [ "$IP" == "$MANAGER_IP" ] ; then
        # we are in a manager
        echo "manager"
    else
        # we are in a node
        echo "node"
    fi
}

# now we call it.
RUN_MODE=$(get_mode)
echo "Starting skywire in '$RUN_MODE' mode"
${SKYWIRE_UNIX_SCRIPTS}/${RUN_MODE}_start
